### ISSUE TITLE
layout wrong with big default font size

### ISSUE THREAD

**Issue by jacekkopecky** [adobe-webplatform/Demo-for-Alice-s-Adventures-in-Wonderland#18]
I use Chrome (39) on Mac 15" Retina with 18px default font size and the layout in the demo is wrong - the text doesn't properly avoid the image countours. The problem seems to be in using em for the size of the scene--alice div, and px for the shape sizes. 

The demo works perfectly if I set my default font size to 16px, and with the size of 18px when I scaled the scene--alice div's height and width to 16/18ths of the original values, it works again. Alternatively, adding "font-size=16px" to body style also fixes everything.

**Comment by oslego** [comment]
Thanks for the pointers, Jacek. Defaulted to using pixels on both scene and shape.
